- .github/main.workflow
When we tag a new version, this will initiate a Github Actions workflow that will build the binaries for each platform and publish them to the Github Release.
> Build and publish binaries on tag

- .github/main.workflow
- .gitignore
- actions/builder/Dockerfile
- actions/builder/README.md
- actions/builder/entrypoint.sh
This adds the version number to the binaries to allow for Terraform provider version restrictions:
```
provider "octopusdeploy" {
version = "~> 0.1.0"
...
}
```
This also ensures windows binaries have the `.exe` extension
> Fix naming of binaries on release

- go.mod
- go.sum
- octopusdeploy/data_machine.go
- octopusdeploy/resource_account.go
- octopusdeploy/resource_machine.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/account.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/channels.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/machines.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/octopusdeploy.go
- vendor/modules.txt
This, along with https://github.com/OctopusDeploy/go-octopusdeploy/pull/17 (which is a dependency for these changes) allows the configuration of Kubernetes deployment targets using terraform.
> Add Kubernetes deployment target support

- octopusdeploy/resource_project.go
- octopusdeploy/resource_project_test.go
Here's an initial attempt I came up with to fix the ordering issue with deployment steps (#27). This PR provides a list wrapper around the deployment steps in order to retain order.
```hcl
resource "octopusdeploy_project" "foo" {
...
deployment_step {
inline_script {
// same as the former deployment_step_inline_script
// under the old format, this would always be second (after the windows_service below)
}
}
deployment_step {
windows_service {
// same as the former deployment_step_windows_service
}
}
}
```
Note: I had lots of issues getting the tests to run in my local test environment, so I'm not 100% sure that I updated them correctly.
> Wrap deployment steps in a list to retain ordering (Resolves #27)

- Makefile
with this we can run acc tests targeting specific tests instead of the whole suite on each run.
example usage:
`make testacc TEST=./octopusdeploy TESTARGS=' -run=TestAccOctopusDeployChannel'`
> added ability to call 'make test' with arguments

- octopusdeploy/resource_certificate.go
There was a bug (found here: https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/issues/63) that would not allow users to update the X509 certs after creating them via Terraform
The issue was the `resourceCertificateUpdate` function in the Terraform provider itself (`resource_certificate.go` ) was pointing to the `Replace` method instead of the `Update` method
I updated the call from `resourceCertificateUpdate` function to instead use the Update method and the update to the cert is successful with no more 500 errors.
Screenshots are in the `topic-terraformprovdr` Slack channel.
> Bug fix for updating X509 certs

- octopusdeploy/data_aws_account.go
- octopusdeploy/data_azure_service_principal.go
- octopusdeploy/data_certificate.go
- octopusdeploy/data_channel.go
- octopusdeploy/data_nuget.go
- octopusdeploy/data_tag_set.go
Created all data resources to match all of the Terraform resources that are available. The data resources will give us the ability to `GET` all of the resource information, for example, if we want to print out data on `certificates` or `projects`.
Please delete options that are not relevant.
> Data resources for Terraform resources

- octopusdeploy/resource_user_role_test.go
- octopusdeploy/schema_user_role.go
Creating a user role with any list properties defined would cause
the provider to crash to a type conversion issue.
Specifying permissions without specify descriptions resulted in a
continuously tainted resource since they are returned by the api. 
Description attributes are now marked as computed and changes 
will not show in plan.
Fixes #149
> fix: Fix user role creation and descriptions

- docs/resources/deployment_process.md
- octopusdeploy/schema_apply_terraform_template_action.go
This change fixes #147 by eliminating the requirement to persist values in the `properties` attribute; the `template` attribute schema has been expanded to incorporate properties required to manage this action.
> fix: resolved tainted behaviour for apply terraform action (#147)

- octopusdeploy/resource_machine_policy_test.go
- octopusdeploy/schema_machine_cleanup_policy.go
- octopusdeploy/schema_machine_connectivity_policy.go
- octopusdeploy/schema_machine_health_check_policy.go
- octopusdeploy/schema_machine_policy.go
- octopusdeploy/schema_machine_script_policy.go
- octopusdeploy/schema_machine_update_policy.go
> fix: implemented more robust support for machine policies

- docs/resources/deployment_process.md
- examples/resources/octopusdeploy_deployment_process/resource.tf
This updates the documentation and example to use the `run_script_action`. The current example throws an error due to the mismatch in `action` vs. `run_script_action`.
Fixes #246
> fix: Update octopusdeploy_deployment_process example to use run_script_action.

- octopusdeploy/schema_space.go
This PR updates the Space schema for Terraform to hide the special Space Managers team from the state file. This team should be an Octopus internal concern, but while it's being returned from the API the easiest option we have for now is to remove it on read and add it back in on updates.
Fixes #306
> Fixed handling of space manager teams

- octopusdeploy/schema_project.go
The project schema was retrieving the SpaceID, and correctly putting it into state but was forgetting to add it back into the object that was being sent to the Octopus API.
Fixes #294
> Project schema wasn't including SpaceID in the data to send to Octopus

- octopusdeploy/schema_deployment_action_container_test.go
- octopusdeploy/schema_team.go
This change will make Terraform no longer respect the order of users in octopusdeploy_team.users. The reason for this change is to stop Terraform from showing changes on the team user list when no users have been added or removed from the list.
> Changed octopusdeploy_team.users to TypeSet from TypeList

- Makefile
- octopusdeploy/config.go
- octopusdeploy/data_source_space.go
- octopusdeploy/data_source_spaces.go
- octopusdeploy/provider.go
- octopusdeploy/schema_queries.go
- octopusdeploy/schema_space.go
This is an alternate solution to #311 that works on the idea of the provider only supporting `space_id`, and making the data source support search for a unique name.
You'd use a config something like
```
provider "octopusdeploy" {
alias   = "unscoped"
address = "http://localhost:8065"
}
data "octopusdeploy_space" "s" {
provider = octopusdeploy.unscoped
name     = "TerraForm test space"
}
provider "octopusdeploy" {
address  = "http://localhost:8065"
space_id = data.octopusdeploy_space.s.id
}
```
Fixes #259
> Update to the space data source, to search by unique name

- go.sum
- octopusdeploy/data_source_git_credentials.go
- octopusdeploy/provider.go
- octopusdeploy/schema_git_credential.go
When the Git Credential support within project was corrected we didn't also include a specific data source for querying existing Git Credentials already being managed within Octopus. This PR adds support for that data source.
Usage:
```
data "octopusdeploy_git_credentials" "test-credential" {
name = "GitHub cred"
}
```
```
resource "octopusdeploy_project" "my-project" {
...
git_library_persistence_settings {
base_path         = ".octopus"
git_credential_id = data.octopusdeploy_git_credentials.test-credential.git_credentials[0].id
url               = "https://github.com/MyOrg/MyProject.git"
}
...
}
```
Fixes #459
> Added Git Credential data source

- docs/data-sources/variables.md
- docs/resources/variable.md
- octopusdeploy/schema_variable.go
- octopusdeploy/schema_variable_prompt_options.go
- octopusdeploy/schema_variable_prompt_options_test.go
Updated the provider to properly support prompted variables.
Example TF config using a prompted variable
```terraform
resource "octopusdeploy_variable" "var1" {
name     = "Database Name"
type     = "String"
value    = "MyDB"
owner_id = octopusdeploy_project.project.id
prompt {
display_settings {
control_type = "Select"
select_option {
value        = "Staging"
display_name = "Staging DB"
}
select_option {
value        = "Production"
display_name = "Prod DB"
}
}
}
}
```
> Fixed handling of prompted variables

- docs/data-sources/projects.md
- docs/resources/project.md
- octopusdeploy/schema_project.go
This PR permits project slugs to be changed through configuration. Minimal validation (i.e. `StringIsNotWhiteSpace`) is enforced through the schema. Validating a slug's uniqueness or checking the API's capability to perform edits on slugs was deemed outside the scope of this change.
Fixes #472
> fix: editable project slugs

- octopusdeploy/schema_dynamic_worker_pool.go
- octopusdeploy/schema_worker_pool.go
Dynamic worker types now support `Ubuntu2204`
> Updated worker_type validation to include new version of Ubuntu

- go.mod
- go.sum
- octopusdeploy/resource_project_deployment_target_trigger.go
When attempting to update an existing space resource, the following error is displayed: The TaskQueueStopped field is required.
Destroying and Creating works fine, but updating existing always expects the TaskQueueStopped value.
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/494
Majority of the changes are done in https://github.com/OctopusDeploy/go-octopusdeploy/pull/189
> Update action on space resource fails

- go.mod
- go.sum
- octopusdeploy/provider.go
- octopusdeploy/resource_runbook.go
- octopusdeploy/resource_runbook_process.go
- octopusdeploy/schema_runbook.go
- octopusdeploy/schema_runbook_process.go
- octopusdeploy/schema_runbook_retention_period.go
This PR adds support for runbooks. An example of the syntax is shown below:
```
data "octopusdeploy_lifecycles" "lifecycle_default_lifecycle" {
ids          = null
partial_name = "Default Lifecycle"
skip         = 0
take         = 1
}
resource "octopusdeploy_project" "deploy_frontend_project" {
auto_create_release                  = false
default_guided_failure_mode          = "EnvironmentDefault"
default_to_skip_if_already_installed = false
description                          = "Test project"
discrete_channel_release             = false
is_disabled                          = false
is_discrete_channel_release          = false
is_version_controlled                = false
lifecycle_id                         = data.octopusdeploy_lifecycles.lifecycle_default_lifecycle.lifecycles[0].id
name …
```
> Add support for runbooks

- octopusdeploy/resource_deployment_process.go
- octopusdeploy/resource_project.go
We shouldn't ever be creating random branches in user's repositories during conversion to VCS.
**Note: In general we would advise against using multiple branches like this in Octopus via the Terraform provider as there may be some unexpected behavior due to the different sources of truth that are now split between the terraform file and the git repository.**
In many cases, the default branch (which I'll refer to as `master` here on) will have no branch protection rules and the user will be able to commit directly to this primary location. For some users however, they may want to define a "default branch" (which is used in currently non VCS areas like runbooks), but not have the ability to push directly to it.
This is simple when dealing with this via the portal since the user can commit …
> Dont force creation of a branch during Cac

- octopusdeploy/schema_kubernetes_cluster_deployment_target.go
This PR provides the ability to create a k8s target with a client certificate like this:
```
resource octopusdeploy_kubernetes_cluster_deployment_target test_eks{
cluster_url                       = var.k8s_cluster_url
environments                      = [
data.octopusdeploy_environments.development.environments[0].id,
data.octopusdeploy_environments.test.environments[0].id,
data.octopusdeploy_environments.production.environments[0].id]
name                              = "Kind"
roles                             = ["k8s"]
cluster_certificate               = ""
machine_policy_id                 = data.octopusdeploy_machine_policies.default_machine_policy.machine_policies[0].id
namespace                         = ""
skip_tls_verification             = true
tenant_tags …
```
> Added the ability to configure a k8s target with a certificate

- octopusdeploy/schema_user_role.go
Fixes bug caused by overly strict validation on Octopus Server where a null collection type is thrown rather than handled as a default.
A more long-term fix will ideally arrive in the Server shortly
> Set missing user role collection properties to empty array

- go.mod
- go.sum
- integration_test.go
- octopusdeploy/resource_runbook_process.go
This PR updates the provider to use the latest version of the Octopus go client and fixes an issue where deleted runbook processes would throw an error if they were reapplied.
> Dependency updates and runbook fix

- integration_test.go
- octopusdeploy/resource_deployment_process.go
- octopusdeploy/resource_runbook_process.go
- octopusdeploy/schema_deployment_action.go
- octopusdeploy/schema_deployment_process.go
- octopusdeploy/schema_deployment_step.go
- octopusdeploy/schema_runbook_process.go
- terraform/45-projectwithscriptactions/project.tf
A behavioural "bug" exists due to the way in which different actions are exposed internally before submitting over the wire. Before we update the plugin framework and leverage some new schema capabilities this change provides a temporary work around.
Actions now provide a `sort_order` property that allows for ordering the different actions within a step. This value is optional and can be omitted entirely, but it is recommended that if setting this property for any, then it should be set for all.
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/445
> Add optional sort_order property to actions

- octopusdeploy/schema_deployment_action.go
Channel version rules used to reference a deployment action by its id. More recent versions of Octopus have changed to using the name reference which is more resilient. This PR makes it compatible with older data.
Shoutout to https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/546 for coming up with the fix.
[[sc-61417](https://app.shortcut.com/octopusdeploy/story/61417/tf-plugin-deployment-step-action-updates-fail-with-octopus-2023-3-requested-by-finnian-dempsey)]
> Retain deployment action id between updates

- octopusdeploy/resource_deployment_process.go
- octopusdeploy/schema_deployment_process.go
Issue https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/556 describes a scenario where assigning an invalid project ID to a deployment process causes the TF provider to crash. This PR catches the case where the project returned by the invalid project ID is nil and displays an error rather than crashing.
The result now looks like this:
```
╷
│ Error: Octopus API error: Resource is not found or it doesn't exist in the current space context. Please contact your administrator for more information. [] 
│ 
│   with octopusdeploy_deployment_process.this,
│   on bug.tf line 54, in resource "octopusdeploy_deployment_process" "this":
│   54: resource "octopusdeploy_deployment_process" "this" {
│ 
╵
```
> Fix crash when Project ID is invalid

- octopusdeploy/resource_deployment_process.go
Intializing empty array for `Steps` property in `deploymentProcess` because
`DeploymentProcesses.Update` calls "/api/Spaces-1/projects/<ProjectID>/deploymentprocesses" but
it fails if `Steps` property is undefined.
> fix: prevent api call failure during deployment process delete

- octopusdeploy/schema_certificate.go
Not all certificates have a password, for example Kubernetes Certificate Authorities.
This PR changes the password field to not be required to support these use-cases.
> Certificate Password Should Be Optional

- .gitignore
- examples/resources/octopusdeploy_account/resource.tf
- go.mod
- go.sum
- octopusdeploy/provider.go
- octopusdeploy/resource_azure_oidc_account.go
- octopusdeploy/resource_azure_oidc_account_test.go
- octopusdeploy/schema_azure_oidc_account.go
- octopusdeploy/schema_queries.go
- octopusdeploy/schema_utilities.go
terraform file
```
resource "octopusdeploy_azure_openid_connect" "oidc" {
application_id  = "82587d26-ee04-4446-aede-9e89b1ff2b4d"
name            = "Azure OpenID Connect Account (OK to Delete)"
subscription_id = "00000000-0000-0000-0000-000000000000"
tenant_id       = "00000000-0000-0000-0000-000000000000"
execution_subject_keys = ["space", "project"]
health_subject_keys = ["space", "target", "type"]
account_test_subject_keys = ["space", "type"]
}
resource "octopusdeploy_azure_service_principal" "azure_service_principal_account" {
application_id  = "00000000-0000-0000-0000-000000000000"
name            = "Azure Service Principal Account (OK to Delete)"
password        = "###########" # required; get from secure environment/store
subscription_id = "00000000-0000-0000-0000-000000000000" …
```
> azure OIDC account support

- .github/workflows/integration-tests.yaml
- integration_test.go
- octopusdeploy/schema_cloud_region_deployment_target.go
This PR fixes the bug at https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/580.
The cloud region data source was the only one that removed the `endpoint` field from the schema. This in turn broke the data source when it tried to flatten targets into the returned results.
Since other data sources leave the `endpoint` field in the schema, this PR removes the line that deletes the `endpoint` field.
To speed up the integration tests, the `hashicorp-forge/go-test-split-action@v1` action has been added. This runts the integration tests across 15 nodes, reducing the test time to under ten minutes (down from an hour).
The tests were also updated to run against Octopus 2023.4.
> Fix the cloud region data source

- docs/data-sources/variables.md
- docs/resources/variable.md
- octopusdeploy/resource_variable.go
- octopusdeploy/schema_variable_scope.go
adds support for scoping project variables to processes
```hcl
resource "octopusdeploy_variable" "string_variable" {
owner_id  = "Projects-123"
type      = "String"
name      = "My String Value (OK to Delete)"
value     = "PlainText"
scope {
process_owners = ["Runbooks-1234"]
}
}
```
fixes #361
> Support proccess scoped variables

- octopusdeploy/data_source_tenants.go
The `tenant_data_source` was not using the new client, which supports the use of `space_id`.
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/586
[sc-67134]
> Fix: Use newclient for tenant datasource

- octopusdeploy/schema_tenant.go
The changes made in 0.14.5 [broke the integration tests](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/actions/runs/7619511193) because the tenants schema did not have a `space_id` field, meaning any attempt to return the `space_id` field when it was not set resulted in a `nil`, which then could not be converted to a `string`.
This PR adds the `space_id` field to the tenants datasource schema.
The crash is:
```
Stack trace from the terraform-provider-octopusdeploy_v0.14.5 plugin:
panic: interface conversion: interface {} is nil, not string
goroutine 425 [running]:
github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.dataSourceTenantsRead({0xffa2c0?, 0xc000a1b3b0?}, 0x0?, {0xdb57e0?, 0xc000165080}) …
```
> Fixed the new tenants data source

- integration_test.go
- octopusdeploy/schema_action_apply_terraform_template.go
- terraform/50-applyterraformtemplateaction/config.tf
- terraform/50-applyterraformtemplateaction/project.tf
- terraform/50-applyterraformtemplateaction/project_group_test.tf
- terraform/50-applyterraformtemplateaction/provider.tf
- terraform/50-applyterraformtemplateaction/provider_vars.tf
- terraform/50-applyterraformtemplateaction/space.tf
- terraform/50-applyterraformtemplateaction/workerpool.tf
The `apply_terraform_template_action` step does not have a `worker_pool_id` attribute, and setting the attribute in the `properties` does not work.
This PR adds the `worker_pool_id` attribute to bring `apply_terraform_template_action` inline with other steps like [run_kubectl_script_action](https://registry.terraform.io/providers/OctopusDeployLabs/octopusdeploy/latest/docs/resources/deployment_process#nested-schema-for-steprun_kubectl_script_action).
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/601
> Add the worker_pool_id field to apply_terraform_template_action steps

- octopusdeploy/schema_action_run_kubectl_script.go
- octopusdeploy/schema_action_run_kubectl_script_test.go
This PR adds ability to specify the Kubernetes namespace on the `run_kubectl_script` step resource.
[sc-71215]
> Add support to specify k8s namespace on kubectl script step

- go.mod
- go.sum
- integration_test.go
- octopusdeploy/schema_variable_prompt_options.go
- octopusdeploy/schema_variable_prompt_options_test.go
Related to https://github.com/OctopusDeploy/go-octopusdeploy/pull/241
The property `PollingRequestMaximumMessageProcessingTimeout` was removed from the Machine Policy resource in 2024.2 and it broke some customers.
In the below example, the property doesn't need to be set. The value will still be set internally as shown in the plan, but the server will drop the value at the API. This allows older servers to still have this value set.
[sc-72087]
resource:
```
resource "octopusdeploy_machine_policy" "machine_policy_1" {
name = "new machine policy"
}
```
result:
```
❯ terraform apply
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource …
```
> fix: removing required attribute `PollingRequestMaximumMessageProcessingTimeout` on machine policy

- octopusdeploy/schema_deployment_action.go
It seems worker_pool_variable is not being applied so it always set an empty value.
First time to add commits here, feel free to let me know if anything is missing.
> Fix the issue for worker_pool_variable not being applied.

- .github/workflows/build.yml
- .github/workflows/release.yml
The go cli version has been updated from 1.20 to 1.21 as part of this [change](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/616). The builds were working fine but the release step [failed](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/actions/runs/8386301220/job/22966492251#step:5:31) as goreleaser wasn't happy. The goreleaser version used in that step was `goreleaser-action/1.24.0/x64/goreleaser` which should support go cli 1.21  https://github.com/goreleaser/goreleaser/releases
> Update go version for the goreleaser

- octopusdeploy/resource_aws_account.go
The changes to support setting spaces on resources seems to have missed aws accounts. This small change fixes that.
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/592
> Use new client method for creating aws account

- docs/resources/deployment_process.md
- docs/resources/external_feed_create_release_trigger.md
- docs/resources/runbook_process.md
- docs/resources/variable.md
- examples/resources/octopusdeploy_variable/resource.tf
- go.mod
- go.sum
- integration_test.go
- octopusdeploy/resource_external_feed_create_release_trigger.go
- octopusdeploy/schema_deployment_action.go
- octopusdeploy/schema_deployment_action_slug_package.go
- octopusdeploy/schema_deployment_action_slug_package_test.go
- octopusdeploy/schema_external_feed_create_release_trigger.go
- octopusdeploy/schema_utilities.go
- terraform/52-packagefeedcreatereleasetrigger/deployment_process.tf
- terraform/52-packagefeedcreatereleasetrigger/feed.tf
- terraform/52-packagefeedcreatereleasetrigger/project.tf
- terraform/52-packagefeedcreatereleasetrigger/project_triggers.tf
- Use the new [version](https://github.com/OctopusDeploy/go-octopusdeploy/pull/245) of the go-octopusdeploy library following the renaming of the `DeploymentAction` field to `DeploymentActionSlug` for `package` references.
- Add a new `primary_package` resource schema for external feed triggers. This will make it easier to distinguish between the two types of packages in Octopus deployment steps, and is easier to remember than otherwise having to set `package_reference = null` for primary packages.
- Make the `space_id` field optional for the external feed trigger resource. This is in line with every other resource in the Octopus TF provider. [sc-77155]
- Includes a [fix](https://github.com/OctopusDeploy/go-octopusdeploy/pull/246) in the go-octopusdeploy library to use the `space_id` in …
> Use DeploymentActionSlugPackage for external feed triggers and add resource schema for primary package references

- octopusdeploy/resource_runbook_process.go
- terraform/51-deploymentprocesswithgitdependency/deployment_process.tf
In order to cater for upcoming runbooks in git functionality, the latest Octopus Server instances will require the projectId value to be set.  This failure is reported through the provider as the following error
```
│ Error: Octopus API error: Object reference not set to an instance of an object. [] 
│
│   with octopusdeploy_runbook_process.runbook,
│   on main.tf line 107, in resource "octopusdeploy_runbook_process" "runbook":
│  107: resource "octopusdeploy_runbook_process" "runbook" {
```
Since we are loading the runbook details before sending the process to the back end, we can take the `ProjectId` off the `Runbook` object and set it on the `RunbookProcess`. This area will need to be reconsidered further as it is supported by Config as Code
Also Fixes test that was relying on a bug …
> Ensure runbookProcess has runbook ProjectId set

- docs/data-sources/machine_policies.md
- docs/resources/machine_policy.md
- go.mod
- go.sum
- integration_test.go
- octopusdeploy/schema_machine_update_policy.go
- terraform/27-machinepolicy/machinepolicy.tf
Adds a new `kubernetes_agent_update_behavior` property to the `machine_policy.machine_update_policy`
Possible values are `Update` and `NeverUpdate`. Default is `Update`
Shortcut story: [sc-78687]
> Add kubernetes_agent_update_behavior to machine_update_policy

- integration_test.go
- octopusdeploy/schema_ssh_key_account.go
- terraform/7-sshaccount/environments.tf
- terraform/7-sshaccount/ssh_account.tf
It looks like the `octopusdeploy_ssh_key_account` is not passing the environments configured on the desired state to the back end.
Fixes: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/255
> correctly pass environments for ssh key account

- octopusdeploy/resource_library_variable_set.go
- octopusdeploy/schema_action_template_parameter.go
- octopusdeploy/schema_library_variable_set.go
When defining new `octopusdeploy_tenant_common_variable` resources, it is nice to be able to reference the library variable set template ID by the template name.
This PR uses the suggestions from https://github.com/hashicorp/terraform/issues/18863 and https://discuss.hashicorp.com/t/custom-provider-how-to-reference-computed-attribute-of-typemap-list-set-defined-as-nested-block/22898/2 to create a lookup map called `template_ids` on a `octopusdeploy_library_variable_set` resource, and modify the plan to ensure the map includes all the new templates that might be added.
> Allow library variable templates to be referenced by name

- octopusdeploy/schema_library_variable_set.go
Fixes: #652 
For the terraform:
```
data "octopusdeploy_library_variable_sets" "platform" {
partial_name = "Variable Set Name"
space_id = data.octopusdeploy_space.space.id
skip = 0
take = 1
}
output "lvs_template_ids" {
value = data.octopusdeploy_library_variable_sets.platform.library_variable_sets[0].template_ids
}
```
before:
```
Changes to Outputs:
+ lvs_template_ids = {}
```
after:
```
Changes to Outputs:
+ lvs_template_ids = {
+ "Common.TP.AnotherOne"    = "71a27af8-8372-4937-aa05-9ce7148df8b7"
+ "Common.TP.Environment"   = "28a603b4-6d4a-4356-b9b0-0ee530c09bdf"
+ "Common.TP.Something"     = "4415c144-9ab8-4306-a665-442e6429bd75"
+ "Common.TP.SomethingElse" = "805a1923-bcdb-4c30-80f6-b875c6f747fd"
+ "Common.TP.Target"        = "734a1e2b-2faa-4759-a652-b555c07eff88"
}
```
> include template_ids in library variable set datasource

- docs/data-sources/library_variable_sets.md
- docs/resources/deployment_process.md
- docs/resources/library_variable_set.md
- docs/resources/runbook_process.md
- octopusdeploy/schema_action_deploy_kubernetes_secret.go
- octopusdeploy/schema_action_deploy_kubernetes_secret_test.go
- octopusdeploy/schema_deployment_action.go
- octopusdeploy/util.go
In the UI, the Kubernetes Object Status Check is enabled by default, however, in the TF provider, this action property is not being set for kubernetes action types.
We only have 1 defined kubernetes action, `deploy_kubernetes_secret_action`, so I've added a new 1st class property, `kubernetes_object_status_check_enabled` that defaults to `true`.
For all other normal `action` blocks, we polyfill the `properties` with the `Octopus.Action.Kubernetes.ResourceStatusCheck` property set to true _if_ the `action_type` is a known Kubernetes action.
This results in the value being correctly sent to the server. However, the property doesn't get saved in the Terraform state, so it means subsequent plans will show a change to remove the property, but any apply after that will then _reapply_ that …
> Enable Kubernetes Object Status Check by default on all Kubernetes steps

- octopusdeploy/provider.go
- octopusdeploy_framework/datasource_environments.go
- octopusdeploy_framework/datasource_feeds.go
- octopusdeploy_framework/datasource_project_groups.go
- octopusdeploy_framework/framework_provider.go
- octopusdeploy_framework/resource_artifactory_generic_feed.go
- octopusdeploy_framework/resource_aws_elastic_container_registry.go
- octopusdeploy_framework/resource_environment.go
- octopusdeploy_framework/resource_github_repository_feed.go
- octopusdeploy_framework/resource_helm_feed.go
- octopusdeploy_framework/resource_maven_feed.go
- octopusdeploy_framework/resource_nuget_feed.go
- octopusdeploy_framework/resource_project_group.go
Also, some small cleanups of the type name in a few resources, preferring using a helper utility over custom formatting in each resource
before:
```
╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider octopus.com/com/octopusdeploy: failed to retrieve schema from provider "octopus.com/com/octopusdeploy": Invalid Provider Server Combination: The combined provider has differing provider schema implementations across providers. Provider schemas must be identical across providers. This is always an issue in the provider
│ implementation and should be reported to the provider developers.
│ 
│ Provider schema difference:   &tfprotov6.Schema{
│       Version: 0,
│       Block: …
```
> chore!: align config in both providers

- docs/data-sources/accounts.md
- examples/resources/octopusdeploy_account/resource.tf
- octopusdeploy/schema_queries.go
- octopusdeploy/schema_utilities.go
The AWS oidc account type was missing from the account types list.
Account created from UI
> Add aws oidc account type

- octopusdeploy_framework/datasource_environments.go
- octopusdeploy_framework/datasource_environments_test.go
- octopusdeploy_framework/schemas/environment.go
```terraform
data "octopusdeploy_environments" "dev" {
name = "Dev"
}
output "dev" {
value = data.octopusdeploy_environments.dev
}
```
```terraform
dev = {
"environments" = tolist([
{
"allow_dynamic_infrastructure" = true
"description" = ""
"id" = "Environments-1"
"jira_extension_settings" = tolist([
{
"environment_type" = "development"
},
])
"jira_service_management_extension_settings" = tolist([])
"name" = "Dev"
"servicenow_extension_settings" = tolist([])
"slug" = "dev"
"sort_order" = 1
"space_id" = "Spaces-1"
"use_guided_failure" = false
},
{
"allow_dynamic_infrastructure" = false
"description" = "test environment"
"id" = "Environments-82"
"jira_extension_settings" = tolist([])
"jira_service_management_extension_settings" = tolist([])
"name" = "DevEnv"
"servicenow_extension_settings" …
```
> chore: when specifying name in datasource we should only return exact match

- octopusdeploy_framework/resource_project_expand.go
- octopusdeploy_framework/resource_project_test.go
- octopusdeploy_framework/resource_tenant_test.go
- octopusdeploy_framework/schemas/project.go
This fixes the IDs on the templates attached to a project from getting new guid ID values everytime they are changed.
before: 
after:
> chore: fix template ids for project 

- go.mod
- go.sum
- octopusdeploy_framework/datasource_feeds.go
This change adds the Name field to feeds search to support the feeds datasource searching in terraform.
```
data "octopusdeploy_feeds" "foo" {
name      = "foo"
feed_type = "Docker"
skip      = 0
take      = 1
}
data "octopusdeploy_feeds" "bar" {
name = "bar"
feed_type = "Docker"
skip      = 0
take      = 1
}
resource "terraform_data" "feeds" {
input = {
foo = data.octopusdeploy_feeds.foo.feeds[0].id, # Feeds-1
bar = data.octopusdeploy_feeds.bar.feeds[0].id, # also Feeds-1
}
}
output "feeds_out" {
value = resource.terraform_data.feeds
}
```
> 
>  ~ feeds_outy = {
>         id               = "17c8e400-62a6-3c69-c884-5beb7e1c5457"
>       ~ input            = {
>           ~ foo = "Feeds-1689" -> "Feeds-1688"
>             # (1 unchanged attribute hidden)
>         }
>       ~ output …
> Fix datasource feeds search not respecting name

- octopusdeploy_framework/schemas/runbook_retention_period.go
Fixes the following error when running `tf apply` after updating `retention_policy`
```
When applying changes to octopusdeploy_runbook.non_tenanted_runbookz, provider "provider[\"octopus.com/com/octopusdeploy\"]" produced an unexpected new value: .retention_policy[0].should_keep_forever: was cty.True, but │ now cty.False.
```
> chore: remove plan modifiers from retention period

- docs/resources/library_variable_set.md
- octopusdeploy_framework/schemas/library_variable_set.go
- octopusdeploy_framework/schemas/schema.go
This fixes the following two issues found in testing:
Fixes [] => null on templates and "" -> null on display settings.
```
Changes to Outputs:
~ lvs  = {
~ id                    = "Library Variables Sets 2024-08-15 02:14:22.495669 +0000 UTC" -> "Library Variables Sets 2024-08-15 02:23:27.676669 +0000 UTC"
~ library_variable_sets = [
~ {
id              = "LibraryVariableSets-81"
name            = "Another Variable Set"
~ template        = [] -> null
},
]
}
~ sms  = {
~ id                    = "Library Variables Sets 2024-08-15 02:14:22.498898 +0000 UTC" -> "Library Variables Sets 2024-08-15 02:23:27.675886 +0000 UTC"
~ library_variable_sets = [
~ {
id              = "LibraryVariableSets-82"
name            = "Hello"
~ template        = [] -> null
},
]
}
```
Unexpected changes, only …
> Chore!: fix lvs datasource unexpected changes and resource Known After Apply differences.

- docs/data-sources/git_credentials.md
- octopusdeploy_framework/datasource_git_credentials.go
- octopusdeploy_framework/schemas/gitCredential.go
The GitCredentials data source includes a password field. This is never actually sent down to the client and is a redundant field. This PR removes it from the data source.
> Update git credential datasource

- octopusdeploy_framework/resource_environment.go
Note: This "fix" is redundant because we don't handle environments moving across spaces. That said it brings the behaviour in line with the old provider and is required to eventually support this behaviour.
Changing an Environments SpaceId in the older provider throws this error
New provider fails with the SpaceId changing
After "Fix"
> Update environment resource testing

- docs/resources/artifactory_generic_feed.md
- examples/resources/octopusdeploy_artifactory_generic_feed/resource.tf
Minor docs update for the AGF example. There's an issue where we trim trailing slashes in Urls. This means the configuration posted vs returned changes. Since this is a required attribute Plan Modifiers do not help.
> Update AGF example

- octopusdeploy_framework/resource_tag.go
- octopusdeploy_framework/resource_tag_set_test.go
- octopusdeploy_framework/resource_tag_test.go
This fixes an issue when migrating tags across tag sets. There were a few problems, the main one being the tag ID was not set after being updated.
> Chore!: Fix migrating tag across sets

- octopusdeploy_framework/data_source_library_variable_sets.go
- octopusdeploy_framework/data_source_script_modules.go
- octopusdeploy_framework/datasource_environments.go
- octopusdeploy_framework/datasource_feeds.go
- octopusdeploy_framework/datasource_git_credentials.go
- octopusdeploy_framework/datasource_lifecycle.go
- octopusdeploy_framework/datasource_project.go
- octopusdeploy_framework/datasource_project_groups.go
- octopusdeploy_framework/datasource_space.go
- octopusdeploy_framework/datasource_spaces.go
- octopusdeploy_framework/datasource_tag_sets.go
- octopusdeploy_framework/datasource_tenants.go
- octopusdeploy_framework/util/logging.go
Adds debug logging to existing migrated data sources:
```
Reading environments with query {IDs:[] Name: PartialName:env Skip:0 Take:30}
Reading environments data source returned 27 items
```
> added debug logging to datasources

- docs/data-sources/tenants.md
- octopusdeploy_framework/datasource_tenants.go
- octopusdeploy_framework/schemas/tenant.go
Given the following configuration, which forces a [deferred read](https://developer.hashicorp.com/terraform/language/data-sources#data-source-lifecycle):
```
terraform {
required_providers {
octopusdeploy = { source = "OctopusDeployLabs/octopusdeploy", version = "0.30.0-beta6" }
external = {
source = "hashicorp/external"
version = "2.3.3"
}
}
required_version = ">= 1.6.0"
}
provider "external" {
}
provider "octopusdeploy" {
address  = "${trimspace(var.octopus_server)}"
api_key  = "${trimspace(var.octopus_apikey)}"
space_id = "${trimspace(var.octopus_space_id)}"
}
variable "octopus_server" {
type        = string
nullable    = false
sensitive   = false
description = "The URL of the Octopus server e.g. https://myinstance.octopus.app."
}
variable "octopus_apikey" {
type        = string …
```
> Fix the tenants datasource blocks

- migration-readme.md
- octopusdeploy_framework/resource_variable.go
fixes #771 
before: 
```
Plan: 1 to add, 0 to change, 0 to destroy.
octopusdeploy_variable.string: Creating...
╷
│ Error: create variable failed
│ 
│   with octopusdeploy_variable.string,
│   on main.tf line 31, in resource "octopusdeploy_variable" "string":
│   31: resource "octopusdeploy_variable" "string" {
│ 
│ Octopus API error: Resource is not found or it doesn't exist in the current space context. Please contact your administrator for more information. [] 
```
after:
```
Plan: 1 to add, 0 to change, 0 to destroy.
octopusdeploy_variable.string: Creating...
octopusdeploy_variable.string: Creation complete after 0s [id=9e0fcce6-1fe3-4fe3-a8ab-7455247be95d]
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
> fix: correct space id support for creating variables

- docs/resources/variable.md
- octopusdeploy_framework/resource_variable.go
- octopusdeploy_framework/resource_variable_test.go
- octopusdeploy_framework/schemas/variable.go
fixes #775 
before:
```
~ resource "octopusdeploy_variable" "string" {
+ encrypted_value = (known after apply)
id              = "5a728184-0d52-4039-9897-58a7f6d63791"
+ key_fingerprint = (known after apply)
name            = "stringvar"
+ space_id        = "Spaces-962"
}
Plan: 0 to add, 1 to change, 0 to destroy.
octopusdeploy_variable.string: Modifying... [id=5a728184-0d52-4039-9897-58a7f6d63791]
╷
│ Error: update variable failed
│ 
│   with octopusdeploy_variable.string,
│   on main.tf line 31, in resource "octopusdeploy_variable" "string":
│   31: resource "octopusdeploy_variable" "string" {
│ 
│ Octopus API error: Resource is not found or it doesn't exist in the current space context. Please contact your administrator for more information. [] 
╵
```
after:
```
Terraform will perform …
```
> fix: read the space id from the plan rather than the state for a variable

- octopusdeploy_framework/datasource_environments.go
- octopusdeploy_framework/datasource_project_groups.go
- octopusdeploy_framework/datasource_spaces.go
- octopusdeploy_framework/datasource_tag_sets.go
[sc-92171]
Fixes: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/779
environments before:
```
+ env_output = {
+ environments = null
+ id           = "Environments 2024-09-10 01:49:17.322748 +0000 UTC"
+ ids          = null
+ name         = null
+ partial_name = "broken"
+ skip         = null
+ space_id     = null
+ take         = null
}
```
environments after:
```
+ output     = {
+ environments = []
+ id           = "Environments 2024-09-10 02:43:19.719235 +0000 UTC"
+ ids          = null
+ name         = null
+ partial_name = "broken"
+ skip         = null
+ space_id     = "Spaces-982"
+ take         = null
}
```
tag sets before:
```
+ output     = {
+ id           = "TagSets-2024-09-10 02:33:49.32293 +0000 UTC"
+ ids          = null
+ partial_name = …
```
> fix: empty datasource results should be empty arrays

- octopusdeploy/data_source_worker_pools.go
> fix: Implement filtering a worker pool by name (#537)

- octopusdeploy_framework/resource_tenant_common_variable.go
Add better detection and a better error message when trying to provide a value for a Common Variable Template, but the Tenant has not yet been connected to a Project that includes the Library Set that defines the template.
fixes #790
* Detection logic feels pretty unstreamlined and verbose; happy for suggestions on more canonical `golang` or a better approach.
* I don't understand why the compiler warning requries error messages to start with a lower-case, that feels a bit uncivilized to me. Am I doing the error message approach wrong?
> fix: log when tenant not associated to common variable template

- octopusdeploy/schema_amazon_web_services_openid_connect_account.go
Value read as int was trying to be cast as string, causes crash.
fixes #629
> fix: octopusdeploy_aws_openid_connect_account crash when setting session_duration

- octopusdeploy/data_source_accounts.go
This message was only intended for the resource not the datasource. We have no alternative provided.
closes #789
> fix: remove account datasource deprecated message

- octopusdeploy/schema_action_run_script.go
Updates deployment action to only add `SubstituteInFiles` to the `EnabledFeatures` when it is not already there.
This will ensure that `SubstituteInFiles` will not be in the `EnabledFeatures` list multiple times when updating the deployment action.
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/641
> fix: only append SubstituteInFiles to EnabledFeatures if its not there

- octopusdeploy/schema_kubernetes_agent_deployment_target.go
- octopusdeploy/schema_kubernetes_agent_worker.go
`machine_policy_id` doesn't get set when creating or updating `octopusdeploy_kubernetes_agent_deployment_target`
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/806
> fix: respect machine policy id in kubernetes agent deployment target

- docs/guides/2-provider-configuration.md
- docs/index.md
- octopusdeploy/config.go
- octopusdeploy/provider.go
- octopusdeploy_framework/config.go
- octopusdeploy_framework/framework_provider.go
- templates/guides/2-provider-configuration.md.tmpl
- templates/index.md.tmpl
This PR adds some small improvements to the auth experience of the Terraform Provider:
* Initialises the internal Go Client with an identifier of "TerraformProvider", which allows us to disambiguate requests are coming from use of the Terraform Provider versus other Go Client consumers in API logs
* Adds fall-through support for the more standard `OCTOPUS_API_KEY` environment variable, which gets set by things like the GitHub Actions Octopus Login action when using an API Key. The existing `OCTOPUS_APIKEY` environment variable is still preferred when present.
* Adds support for OIDC Bearer Tokens to be used, either directly configured on the provider, or with the `OCTOPUS_ACCESS_TOKEN` environment variables (which the GitHub Actions Octopus login action sets when using OIDC auth)
* …
> feat: add support for OIDC bearer tokens to auth TFP against Octopus API

- CONTRIBUTING.md
- README.md
Updated readme to provide guidance on new resources.
> chore: update README for framework migration

- docs/data-sources/kubernetes_cluster_deployment_targets.md
- docs/resources/kubernetes_cluster_deployment_target.md
- octopusdeploy/schema_kubernetes_azure_authentication.go
Affected resource: `octopusdeploy_kubernetes_cluster_deployment_target`
`admin_login` attribute is specific to `azure_service_principal_authentication`, but available only on endpoint's authentication block, which is flattened representation of different authentication types, and not getting mapped to the azure authentication.
This PR adds new attribute `admin_login` to `azure_service_principal_authentication`.
Fixes: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/341
> Add admin_login attribute to azure authentication block

- docs/data-sources/tenants.md
- docs/resources/tenant.md
- octopusdeploy_framework/resource_tenant.go
- octopusdeploy_framework/resource_tenant_migration_test.go
- octopusdeploy_framework/schemas/tenant.go
**Background**
Our terraform provider creates invalid plans for a lot of the resources because we are using lists that are intended to be ordered. This is fine with other resources, because it is "tolerated because of the legacy plugin SDK".
There has been a recent update on this resource to use the newer terraform framework - and we no longer have this exemption. This PR addresses this.
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/802
[sc-97302]
> Fix tenant tags producing inconsistent result after apply after updating to plugin framework

- docs/guides/2-provider-configuration.md
- templates/guides/2-provider-configuration.md.tmpl
When I used the example I got:
```
│ Error: Invalid source
│
│   on main.tf line 4, in terraform:
│    4:       source = OctopusDeployLabs/octopusdeploy
│
│ Source must be specified as a string.
```
It seems in most other places it's already quoted.
> Quoted provider value

- octopusdeploy_framework/resource_step_template.go
- octopusdeploy_framework/schemas/step_template.go
closes #827
closes #826
closes #829
> fix: step template issues

- octopusdeploy_framework/resource_variable.go
> fix: same variable with a different scope now gets an ID

- docs/resources/deployment_process.md
- docs/resources/runbook_process.md
- octopusdeploy/schema_action_manual_intervention_test.go
- octopusdeploy/schema_manual_intervention_action.go
- octopusdeploy/util.go
`manual_intervention_action` block was missing attribute to prevent concurrent deployments during intervention, because it's value was set to 'false" by default.
Fixes: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/242
> Add 'Block Deployments' attribute to manual intervention step

- octopusdeploy_framework/resource_environment_test.go
- octopusdeploy_framework/schemas/environment.go
Replace environment resource when `space_id` is changed, at this moment resource update will fail because application cannot find existing environment in space of new `space_id`
Fixes: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/639
> Replace environment resource when space_id is updated

- octopusdeploy/resource_kubernetes_agent_deployment_target.go
- octopusdeploy/schema_kubernetes_agent_deployment_target.go
Resource `octopusdeploy_kubernetes_agent_deployment_target` stores `uri` value as 'Uri' type which is, when returned by the server, is represented as lowercase string. When provided `uri` value has different casing, this is causing Terraform state drift. 
We can "ignore" casing difference by applying `DiffSuppressFunc` to the attribute
Fixes: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/718
> Suppress non-functional difference of URI value

- octopusdeploy_framework/framework_provider.go
Hadn't properly mapped the value through for the framework provider config, but seems that sdk should be fine.
fixes #853
> fix: map access_token through properly from provider config

- docs/guides/breaking-changes-policy.md
- templates/guides/breaking-changes-policy.md.tmpl
This PR adds documentation to the repo and Provider docs, establishing a policy for how Octopus will handle breaking changes when they become necessary in the Terraform Provider. 
The aim of this policy is to balance reasonableness to our customers, and appreciation of the complexity and effort that goes into migrating Terraform Config, with our ability to change the shape of the Provider and its resources over time in order to create a first-class experience for our Terraform users.
> docs: add Breaking Changes policy

- .github/workflows/integration-tests.yaml
- docs/resources/project_versioning_strategy.md
- examples/resources/octopusdeploy_project_versioning_strategy/resource.tf
- octopusdeploy_framework/resource_project_versioning_strategy.go
- octopusdeploy_framework/schemas/entity_schema.go
- octopusdeploy_framework/schemas/project_versioning_strategy.go
The Template and DonorPackage on a Project Versioning Strategy are mutually exclusive options, but this isn't reflected in the schema or our internal translation logic between TF State and API Resources.
Our mapping logic between the TF State and the API Resource didn't account for this, which causes #855 - the provider works fine if the `donor_package` approach is used, but crashes if the `template` approach is used. 
I took the opportunity to also fix up the schema, validation, docs and examples to better represent the actual valid inputs from the Octopus Server perspective:
* Changed `donor_package` in the schema from Required to Optional
* Changed child attributes of `donor_package` to be required, when `donor_package` is present
* Added new validation that checks that:
1. Both …
> fix: panic using project_verisoning_strategy without donorpackage

- docs/guides/breaking-changes-list.md
- docs/guides/migration-guide-v0.8.0.md
- templates/guides/breaking-changes-list.md.tmpl
- templates/guides/migration-guide-v0.8.0.md.tmpl
- Fix nav structure
- Fix a dodgy table
> docs: fix nav structure

- docs/guides/breaking-changes-list.md
- templates/guides/breaking-changes-list.md.tmpl
One more tiny fix to the nav structure of the docs
From this:
To this:
> docs: breaking changes list section fix

- docs/data-sources/user_roles.md
- docs/resources/user_role.md
- octopusdeploy/schema_user_role.go
fixes #539 
I could not get this resource to migrate to framework while maintain backwards compatibility. In addition because of the way our API works a resource like this would not work well in framework. This is because if the granted space permission are invalid instead of throwing an error the API would automatically include the "missing" permission causing terraform plugin framework to always complain the plan does not match the outcome.
This is a fix stop reordering in SDK, in the future we can consider a new resource framework that would not need to carry over the legacy of this resource. Creating the new resource now would have little benefit over this fix.
Despite the schema changes, no migration is needed.
> fix: granted space permissions forcing UI order

- go.mod
- go.sum
- octopusdeploy_framework/resource_script_module_test.go
```terraform
data "octopusdeploy_script_modules" "example" {
skip         = 0
}
output "data_lookup" {
value = data.octopusdeploy_script_modules.example.script_modules[0]
}
```
```terraform
+ data_lookup = {
+ description     = ""
+ id              = "LibraryVariableSets-82"
+ name            = "Hello"
+ script          = [
+ {
+ body   = ""
+ syntax = ""
},
]
+ space_id        = "Spaces-1"
+ variable_set_id = "variableset-LibraryVariableSets-82"
}
```
```terraform
+ data_lookup = {
+ description     = ""
+ id              = "LibraryVariableSets-82"
+ name            = "Hello"
+ script          = [
+ {
+ body   = <<-EOT
function Say-Hello()
{
Write-Output "Hello, Octopus!"
}
EOT
+ syntax = "PowerShell"
},
]
+ space_id        = "Spaces-1"
+ variable_set_id = …
```
> fix: update octopus go client to populate script syntax and body

- docs/resources/process.md
- examples/resources/octopusdeploy_process/resource.tf
- octopusdeploy_framework/process_wrapper.go
- octopusdeploy_framework/resource_process.go
- octopusdeploy_framework/resource_process_child_step.go
- octopusdeploy_framework/resource_process_child_step_mapping_test.go
- octopusdeploy_framework/resource_process_child_step_test.go
- octopusdeploy_framework/resource_process_child_steps_order.go
- octopusdeploy_framework/resource_process_child_steps_order_mapping_test.go
- octopusdeploy_framework/resource_process_child_steps_order_runbook_test.go
- octopusdeploy_framework/resource_process_step.go
- octopusdeploy_framework/resource_process_step_mapping_test.go
- octopusdeploy_framework/resource_process_step_test.go
- octopusdeploy_framework/resource_process_steps_order.go
- octopusdeploy_framework/resource_process_steps_order_mapping_test.go
- octopusdeploy_framework/resource_process_steps_order_test.go
- octopusdeploy_framework/resource_process_test.go
- octopusdeploy_framework/schemas/process.go
Adds support for runbooks in new `octopusdeploy_process` resource
Runbook process have similar data structure as deployment process, but using different API endpoints
```terraform
resource "octopusdeploy_process" "copy_database" {
project_id = octopusdeploy_project.app.id
runbook_id = octopusdeploy_runbook.copy_database.id
}
```
> Support runbooks for new process resource

- Makefile
Updated makefile to run the correct command for docs generation. The previous was producing unexpected changes
Context: https://octopusdeploy.slack.com/archives/C056NSRCRAL/p1744247970616289
> chore: updated docs command in makefile

- octopusdeploy_framework/resource_project.go
When migrating the project resource to framework, it seems we missed the import function for project.
> fix: import state for project resource missing

- octopusdeploy_framework/process_wrapper.go
- octopusdeploy_framework/resource_process.go
- octopusdeploy_framework/resource_process_child_step.go
- octopusdeploy_framework/resource_process_child_steps_order.go
- octopusdeploy_framework/resource_process_step.go
- octopusdeploy_framework/resource_process_steps_order.go
Importing of `octopusdeploy_process` resources is failing at this moment, because provider trying to load corresponding project before loading process to check if project is version controlled.
This PR sets project id to the state during import by using similar "loading" approach we use for process steps
> Set project id when importing existing process

- docs/guides/migration-guide-v1.0.0.md
- templates/guides/migration-guide-v1.0.0.md.tmpl
Guide to migrate to version v1.0.0 of the Terraform Provider
> chore: migration guide for v1.0.0

- octopusdeploy_framework/schemas/lifecycle.go
Background:
Computed attributes were always shown as "known after apply" in the plan.
Fixes: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/904
```terraform
resource "octopusdeploy_lifecycle" "web_app" {
name        = "Web application"
description = "Lifecycle for web application continous deployment (reset)"
release_retention_policy {
quantity_to_keep    = 0
should_keep_forever = true
unit                = "Days"
}
tentacle_retention_policy {
quantity_to_keep    = 30
should_keep_forever = false
unit                = "Items"
}
phase {
name                         = "Experiment"
automatic_deployment_targets = [module.predefined.environments.development, module.predefined.environments.testing]
release_retention_policy {
quantity_to_keep    = 1 …
```
> Add "UseStateForUnknown" plan modifier for lifecycle phase attributes

- docs/resources/process_child_step.md
- docs/resources/process_step.md
- docs/resources/process_templated_child_step.md
- docs/resources/process_templated_step.md
- examples/resources/octopusdeploy_process_step/resource.tf
- octopusdeploy_framework/resource_process_child_step.go
- octopusdeploy_framework/resource_process_child_step_mapping_test.go
- octopusdeploy_framework/resource_process_step.go
- octopusdeploy_framework/resource_process_step_mapping_test.go
- octopusdeploy_framework/resource_process_templated_child_step.go
- octopusdeploy_framework/resource_process_templated_step.go
- octopusdeploy_framework/schemas/process_child_step.go
- octopusdeploy_framework/schemas/process_step.go
- octopusdeploy_framework/schemas/process_step_reserved_execution_properties_validator.go
- octopusdeploy_framework/schemas/process_templated_child_step.go
- octopusdeploy_framework/schemas/process_templated_step.go
`primary_package` is special case in set of packages of process action. For package to be considered as primary package it's key should be an empty string `""`, Server will automatically add "legacy" properties to the set of action properties, which can lead to state conflicts between planned and applied terraform configurations
Primary package wraps this logic into dedicated attribute and make sure that automatically generated property will not cause state drift issues
```terraform
resource "octopusdeploy_process_step" "one" {
process_id = octopusdeploy_process.app.id
name = "One"
condition = "Success"
type = "Octopus.Script"
is_required = true
is_disabled = false
execution_properties = {
"Octopus.Action.Script.ScriptSource" = "Package"
"Octopus.Action.Script.ScriptFileName" = …
```
> Introduce primary_package attribute for new process step
