- README.md
- go.mod
- go.sum
- octopusdeploy/config.go
- octopusdeploy/provider.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/action_template_parameter.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/common_models.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/octopusdeploy.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/property_value_resource.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/space.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/util.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/variables.go
- vendor/modules.txt
This PR allows a given Terraform provider configuration to be scoped to a single Space. All resources managed by the provider will be in the given space. Managing multiple spaces will require multiple provider instances using aliases (see README).
> Basic support for Spaces.

- octopusdeploy/resource_variable.go
This adds basic support for sensitive variables. The values of sensitive variables will be in plain text in the Terraform output and state file. We show a warning in this case to make the user aware of this. I've created #23 to capture a future enhancement that will allow encrypting the value locally using PGP.
> Add basic support for sensitive variables

- go.mod
- go.sum
- octopusdeploy/provider.go
- octopusdeploy/resource_certificate.go
- octopusdeploy/resource_certificate_test.go
- octopusdeploy/resource_project.go
- octopusdeploy/util.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/certificate.go
- vendor/github.com/OctopusDeploy/go-octopusdeploy/octopusdeploy/octopusdeploy.go
- vendor/modules.txt
This adds support for Certificate resources.
**NOTE**: This cannot be merged until it includes the bug fix in this PR: https://github.com/OctopusDeploy/go-octopusdeploy/pull/14
> Add support for certificates

- octopusdeploy/resource_project.go
I needed the Kubernetes Deployment step to fully automate some pipelines.
Let me know of any improvements needed.
I'll probably add some better descriptions for each variable in an upcoming commit.
Maybe should also rename the function to be more helm centric.
But it does work :D
> feat(terraform): Kubernetes Helm + Raw Yaml deployment steps

- octopusdeploy/data_feed.go
- octopusdeploy/provider.go
> GH-44 Add feed data source

- README.md
- examples/main.tf
- website/docs/r/project.html.markdown
The example (`examples/main.tf`) was not using the correct syntax to add
deployment steps.
> Fix example

- octopusdeploy/resource_project.go
> Updated Helm Deployment Step to take in client_version

- examples/Project-Creation/terraform.tfvars
- examples/Project-Creation/variables.tf
- examples/Project-Group-Creation/terraform.tfvars
- examples/Project-Group-Creation/variables.tf
- examples/how-to-install-the-octopus-deploy-terraform-provider.md
I've added in the following:
1. An example on how to create a project group.
2. An example on how to create a project.
3. Steps on how to pull down and use the Terraform provider as a third-party installation.
> Added in examples and documentation

- go.mod
- go.sum
- octopusdeploy/provider.go
- octopusdeploy/resource_aws_account.go
Rough cut of adding the AWS Account as an alternative to #80
> Added AWS Account resource

- octopusdeploy/resource_aws_account.go
- octopusdeploy/resource_usernamepassword_account.go
Resource updates for AWS and UsernamePassword accounts
> Updates resources for AWS and UsernamePassword accounts

- octopusdeploy/accounts.go
- octopusdeploy/resource_usernamepassword_account.go
Example to show the concept. This has not been tested and there are a still a few missing things from the client resources.
> Extracted common account schema and read/update functionality

- octopusdeploy/resource_team_test.go
- octopusdeploy/schema_team.go
> fix: create team with space ID supported

- docs/data-sources/environments.md
- docs/resources/environment.md
- octopusdeploy/resource_cloud_region_deployment_target_test.go
- octopusdeploy/resource_deployment_target_test.go
- octopusdeploy/resource_environment_test.go
- octopusdeploy/resource_listening_tentacle_deployment_target_test.go
- octopusdeploy/schema_environment.go
> fix: set sort_order to an optional attribute

- docs/data-sources/project_groups.md
- docs/resources/project_group.md
- examples/resources/octopusdeploy_project_group/resource.tf
- octopusdeploy/schema_project_group.go
* removed environments from project groups
* updated documentation
* fixes #157
> fix: removed environments from project groups

- docs/data-sources/variables.md
- docs/resources/variable.md
- go.mod
- go.sum
- octopusdeploy/data_source_variables.go
- octopusdeploy/resource_variable.go
- octopusdeploy/resource_variable_test.go
- octopusdeploy/schema_variable.go
- octopusdeploy/schema_variable_scope.go
- octopusdeploy/schema_variable_scope_test.go
- octopusdeploy/util.go
- octopusdeploy/util_test.go
> Fix variable scope

- docs/data-sources/variables.md
- docs/resources/variable.md
- go.mod
- go.sum
- octopusdeploy/data_source_variables.go
- octopusdeploy/resource_variable.go
- octopusdeploy/schema_action_template_parameter.go
- octopusdeploy/schema_extension_settings_values.go
- octopusdeploy/schema_project.go
- octopusdeploy/schema_variable.go
- octopusdeploy/schema_variable_scope.go
> fix: updated variables and underlying dependencies (#153)

- go.mod
- go.sum
- octopusdeploy/resource_variable.go
- octopusdeploy/resource_variable_test.go
> Fix delete operation for variables

- examples/Library-VariableSet-Creation/main.tf
> Update main.tf - Change provider apikey -> api_key

- octopusdeploy/schema_variable_scope.go
> fix: removed process_owners (invalid)

- docs/data-sources/teams.md
- docs/resources/team.md
- octopusdeploy/schema_team.go
> fix: updated teams schema to properly process groups

- octopusdeploy/schema_action_apply_terraform_template.go
- octopusdeploy/schema_action_deploy_windows_service.go
- octopusdeploy/schema_deployment_action.go
- octopusdeploy/schema_package_reference.go
> fix: corrected boolean property serialisation

- README.md
> Added section for environment variables available to configure the provider

- .goreleaser.yml
This should allow us to have 3 sections in our release notes, here is an example:
Example syntax `feat[area]: My awesome new feature`
Example syntax `break[area]: Something won't work anymore`
Example syntax `bug[area]: Squashed another bug`
> Configure changelog

- examples/resources/octopusdeploy_variable/import.sh
- examples/resources/octopusdeploy_variable/resource.tf
- templates/resources/variable.md.tmpl
> Update variable docs to include example usages

- octopusdeploy/resource_deployment_process_test.go
- octopusdeploy/schema_package_reference.go
> Added Check for Name; Applies to Primary Packages

- octopusdeploy/schema_channel.go
> fix: persists channel ID to state

- go.mod
- go.sum
- octopusdeploy/schema_project.go
> fix: update API client to resolve behaviour with spaces in projects

- .goreleaser.yml
> hack: temporarily remove Windows ARM-64

- .github/workflows/build.yml
- .github/workflows/release.yml
> chore: update to Go 1.19

- octopusdeploy/schema_action_apply_terraform_template.go
This is the same as https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/479, but without any tests.
> Fixed terraform apply template step

- docs/resources/tag_set.md
- examples/resources/octopusdeploy_tag_set/resource.tf
> fix: updated documentation for tag_set resource

- docs/resources/lifecycle.md
- octopusdeploy/schema_lifecycle.go
- octopusdeploy/schema_lifecycle_test.go
- octopusdeploy/schema_phase.go
- octopusdeploy/schema_phase_test.go
- octopusdeploy/schema_retention_period.go
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/489
> Lifecycle phase not honouring retentions being set

- octopusdeploy/schema_space.go
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/503
> octopusdeploy_space - always shows changes

- octopusdeploy/data_source_variables.go
- octopusdeploy/schema_variable.go
> fix: data source variables not working

- internal/projects/extension_settings.go
Fix for https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/526
> chore: Change servicenow extension setting to optional

- .gitignore
- Makefile
- examples/resources/octopusdeploy_artifactory_generic_feed/import.sh
- examples/resources/octopusdeploy_artifactory_generic_feed/resource.tf
- go.mod
- go.sum
- octopusdeploy/provider.go
- octopusdeploy/resource_artifactory_generic_feed.go
- octopusdeploy/resource_artifactory_generic_feed_test.go
- octopusdeploy/schema_artifactory_generic_feed.go
Depends on https://github.com/OctopusDeploy/go-octopusdeploy/pull/221
creating new feed:
modify existing feed
delete a feed:
> feat: artifactory generic feed

- go.mod
- go.sum
- octopusdeploy/resource_deployment_process.go
- octopusdeploy/schema_deployment_process.go
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/584
[sc-67101]
> feat: support space_id for deployment process

- docs/index.md
- templates/index.md.tmpl
Fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/555
> Update docs on spaces

- octopusdeploy/resource_aws_openid_connect_account.go
Fixes: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/632
Pulling in changes from https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/631 with a slight tweak
Thanks @joechchung
> Update OIDC aws account

- .github/workflows/release.yml
`rm-dist` has been deprecated https://goreleaser.com/deprecations/#-rm-dist
> fixed go-releaser deprecated option

- .goreleaser.yml
As per https://github.com/goreleaser/goreleaser/pull/4806
> chore: update goreleaser config for breaking change

- octopusdeploy/resource_tenant_common_variable.go
There is a hidden relationship between a tenant, project, library variable set, and library variable set common variables that can make it hard to debug the creation of a octopusdeploy_tenant_common_variable resource. This PR adds additional logging to the error message to help understand what projects a tenant is linked to. The new error looks like this:
```
│ Error: The tenant NX(Tenants-1021) is linked to the following projects and environments:
│ Projects-6543:Environments-3601, Environments-3602, Environments-3603
│ The tenant must be linked to a project that references the library variable set that defines the common variable.
│ The tenant common variable was not found in any projects linked to the tenant.
│ 
│   with octopusdeploy_tenant_common_variable.tenantcommonvariable1_nx,
│ …
```
> Add additional logging when octopusdeploy_tenant_common_variable fails

- docs/resources/environment.md
- octopusdeploy_framework/schemas/environment.go
- octopusdeploy_framework/util/schema.go
> chore: update environment resource and datasource docs

- octopusdeploy_framework/resource_artifactory_generic_feed.go
- octopusdeploy_framework/resource_aws_elastic_container_registry.go
- octopusdeploy_framework/resource_docker_container_registry.go
- octopusdeploy_framework/resource_github_repository_feed.go
- octopusdeploy_framework/resource_helm_feed.go
- octopusdeploy_framework/resource_library_variable_set.go
- octopusdeploy_framework/resource_maven_feed.go
- octopusdeploy_framework/resource_nuget_feed.go
- octopusdeploy_framework/resource_script_module.go
- octopusdeploy_framework/resource_tenant.go
Adds import state to previously migrated resources where it was dropped.
> Chore!: Add import state to migrated resources

- octopusdeploy_framework/datasource_space.go
> Chore!: Fix spaces datasource mapping name

- .github/workflows/docs.yml
Update docs validation so new schemas are required.
[New Schema causes failure](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/actions/runs/10412364844/job/28837999416)
[Passes after docs are included](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/actions/runs/10412391837/job/28838076342)
> Docs validation update

- octopusdeploy_framework/resource_library_variable_set_test.go
- octopusdeploy_framework/schemas/variable_prompt_options.go
Fix issue with variable option
> Fix MapFromSelectOptions - Use correct object type 

- octopusdeploy_framework/datasource_tenant_projects.go
- octopusdeploy_framework/resource_tenant_project.go
- octopusdeploy_framework/schemas/tenant_projects.go
fix: showing duplicates while fetching by project.
chore: made fetching by project concurrent
> chore: refactored tenant project

- octopusdeploy/data_source_worker_pools.go
Related issues:
- https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/536
> fixes #536; Implement filtering a worker pool by name

- octopusdeploy_framework/resource_tenant_project_variable.go
This PR adds a check to ensure that the project template exists before attempting to read any details about it. This fixes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/832.
> fix: Validate that the project template exists before reading it

- docs/guides/migration-guide-v0.37.1.md
- templates/guides/migration-guide-v0.37.1.md.tmpl
More small formatting fixes :man-shakes-fist-at-markdown:
> docs: small fixes in migration guide v0.37.1 content

- docs/resources/variable.md
- octopusdeploy_framework/schemas/variable.go
closes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/488
> chore: marked variable.isEditable as deprecated 

- octopusdeploy_framework/resource_built_in_trigger.go
- octopusdeploy_framework/resource_built_in_trigger_mapping_test.go
- octopusdeploy_framework/resource_project.go
Fixes: https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/875
> Handle missing release creation strategy in Build-in trigger resource

- docs/data-sources/channels.md
- go.mod
- go.sum
- octopusdeploy/data_source_channels.go
- octopusdeploy/schema_channel.go
Add projectID to channel data source
closes https://github.com/OctopusDeploy/go-octopusdeploy/issues/72
> Add projectID filter to channel data source

- docs/data-sources/step_template.md
- docs/resources/step_template.md
- go.mod
- go.sum
- octopusdeploy_framework/datasource_step_template.go
- octopusdeploy_framework/resource_step_template.go
- octopusdeploy_framework/schemas/step_template.go
Add git dependencies to step template resource.
closes https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/873
> Add git dependencies to step template resource

- docs/resources/certificate.md
- octopusdeploy/provider.go
- octopusdeploy_framework/framework_provider.go
- octopusdeploy_framework/resource_certificate.go
- octopusdeploy_framework/resource_username_password_account.go
- octopusdeploy_framework/schemas/certificate.go
- octopusdeploy_framework/schemas/schema.go
> Migrate certficate resource to plugin framework

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Update issues template to direct to new repo.
> chore: update issues template
